version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - fredrikhr
  ignore:
  - dependency-name: YamlDotNet
    versions:
    - 10.0.0
    - 10.1.0
    - 11.0.1
    - 11.1.0
    - 9.1.4
  - dependency-name: Octokit
    versions:
    - 0.49.0
- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - fredrikhr
